### ISSUE TITLE
Issue with the interface

### ISSUE THREAD

**Issue by thepotla** [piyushiiitn/Amanda--NLP-Based-Chatbot#1]
I tried running this after all the installations and the one thing that doesn't work is the interface. The responses don't seem to pop up on the screen, but as you can see in the second picture, the debugging process shows a recorded query and answer. Could you tell me what I can do to fix this?

I've installed python 2.7 and kivy 1.10. 
![1](https://user-images.githubusercontent.com/36852419/37696520-1feded46-2cfd-11e8-8886-aaf845aa4e35.jpg)
![2](https://user-images.githubusercontent.com/36852419/37696521-20204d04-2cfd-11e8-8823-65901d5b50e8.jpg)

Could there be a problem with the kivy packages?

**Comment by tiwo19** [comment]
Hi there i have the sam
![captuhhre](https://user-images.githubusercontent.com/30261634/53398037-f210ff80-39a8-11e9-8aba-dc80543855e8.PNG)
e issue can anybody help

**Comment by anmolgoyal94** [comment]
Hi,
**>>> import nltk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python2.7/site-packages/nltk/__init__.py", line 143, in <module>
    from nltk.chunk import *
  File "/home/ubuntu/.local/lib/python2.7/site-packages/nltk/chunk/__init__.py", line 155, in <module>
    from nltk.data import load
  File "/home/ubuntu/.local/lib/python2.7/site-packages/nltk/data.py", line 45, in <module>
    from gzip import GzipFile, WRITE as GZ_WRITE
  File "/usr/local/lib/python2.7/gzip.py", line 9, in <module>
    import zlib
ImportError: No module named zlib**
 Error is found
Please help me and provide solution for it.
Thanks in advance.
